cinema5/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('auth/', include('allauth.urls')),
    # path('auth/', include('django.auth.contrib')),
    path('', include('movie.urls')),
    path('<slug:slug>/order/', include('order.urls')),
    path('<slug:slug>/payment/', include('payment.urls')),
    path('account/', include('user.urls')),
    path('<slug:city_slug>/promotion/', include('shares.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movie/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.CitiesView.as_view(), name='cities'),
    path('<slug:slug>/today', views.MovieTodayView.as_view(), name='today'),
    path('<slug:slug>/children', views.MovieChildrenTodayView.as_view(), name='children'),
    path('<slug:slug>/date', views.MovieDateView.as_view(), name='filter'),
    path('<slug:slug>/tomorrow', views.MovieTomorrowView.as_view(), name='tomorrow'),
    path('<slug:slug>/soon', views.MovieSoonView.as_view(), name='soon'),
    path('<slug:slug>/today/<int:pk>', views.MovieDetailToday.as_view(), name='movie_detail_today'),
    path('<slug:slug>/tomorrow/<int:pk>', views.MovieDetailTomorrow.as_view(), name='movie_detail_tomorrow'),
    path('<slug:slug>/soon/<int:pk>', views.MovieDetailSoon.as_view(), name='movie_detail_soon'),
    path('<slug:slug>/date/<str:date>/<int:pk>', views.MovieDetailDate.as_view(), name='movie_detail_date'),
    path('<slug:slug>/shows/<int:pk>', views.SessionDetail.as_view(), name='session_detail'),
    path('<slug:slug>/shows/<int:pk>/create/ticket', views.CreateTicket.as_view(), name='create_ticket'),
    path('<slug:slug>/support/', views.SupportView.as_view(), name='support'),
    path('<slug:slug>/about/<int:pk>', views.AboutView.as_view(), name='about'),
    path('<slug:slug>/questions', views.TitleQuestionView.as_view(), name='questions'),
    path('<slug:slug>/questions/<int:pk>', views.AnswerDetailView.as_view(), name='answer'),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import (LogoutView, 
	PasswordResetView, PasswordResetConfirmView,
	PasswordResetDoneView, PasswordResetCompleteView)

from . import views
from .forms import AdvPasswordResetForm, AdvPasswordChangeForm

urlpatterns = [
	path('check', views.CheckPhone.as_view(), name='check_phone'),
	path('use_bonuses/', views.CreateUserOrderView.as_view(), name='use_bonuses'),
	path('check_email/', views.CheckEmail.as_view(), name='check_email'),
	path('acoount/', views.Account.as_view(), name='account'),
	path('account/logout', LogoutView.as_view(), name='logout'),
	path('account/password_reset', PasswordResetView.as_view(
		template_name='user/password_reset.html',
		email_template_name='user/password_reset_email.html',
		form_class=AdvPasswordResetForm
		), name='password_reset'),
	path('account/password_reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
		template_name='user/password_reset_confirm.html',
		form_class=AdvPasswordChangeForm), name='password_reset_confirm'),
	path('account/password_reset/done', PasswordResetDoneView.as_view(
		template_name='user/password_reset_done.html'), name='password_reset_done'),
	path('account/password_reset/complete', PasswordResetCompleteView.as_view(
		template_name='user/password_reset_complete.html'
		), name='password_reset_complete'),
	path('account/update_user/<int:pk>/', views.UpdateAccountView.as_view(), name='update_user'),
]

movie/models.py
from django.db import models
from django.utils import timezone

from order.models import Order
# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name


class Movie(models.Model):
    """Movie model"""
    title = models.CharField(max_length=100)
    city = models.ManyToManyField(City)
    age_limit = models.ForeignKey('AgeLimit', on_delete=models.CASCADE)
    country = models.CharField(max_length=200)
    genres = models.CharField(max_length=200, blank=True)
    director = models.CharField(max_length=100, blank=True, null=True)
    actors = models.CharField(max_length=200, blank=True)
    duration = models.TimeField(blank=True, null=True)
    poster = models.ImageField(upload_to='images/movies/%Y/%M/%D', blank=True)
    memorandum = models.DateField(auto_now_add=True, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField(auto_now=True)
    premier = models.BooleanField(default=False)
    carousel = models.ImageField(upload_to='images/movies/carusel/%Y/%M/%D', blank=True)
    is_carousel = models.BooleanField(default=False)
    trailer = models.URLField(blank=True, null=True)
    # cinemas = models.ManyToManyField('Cinema')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)


class AgeLimit(models.Model):
    """Age Limit model"""
    name = models.CharField(max_length=3)
    for_adults = models.BooleanField(default=True if name=='18+' else False)

    def __str__(self):
        return self.name


class Cinema(models.Model):
    """Cinema model"""
    name = models.CharField(max_length=100)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    phone = models.CharField(max_length=11, default='')
    information = models.TextField(default='')
    halls = models.IntegerField(default=0)
    places = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name} - {self.city}"


class Session(models.Model):
    """Session model"""
    date = models.DateField()
    time = models.TimeField()
    format = models.CharField(max_length=10)
    hall = models.ForeignKey('Hall', on_delete=models.CASCADE)
    cinema = models.ForeignKey(Cinema, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    # city = models.ForeignKey(City, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    price = models.IntegerField(default=228)

    def __str__(self):
        return f"{self.movie.title} - {self.date} - {self.time} - {self.cinema}"


class Hall(models.Model):
    """cinema hall"""
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Row(models.Model):
    row = models.IntegerField()
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

    def __str__(self):
        return f"ряд {self.row} - {self.hall.name}"


class Place(models.Model):
    """place in the cinema hall"""
    row = models.ForeignKey(Row, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    empty = models.BooleanField(default=False)
    place = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"Ряд №{self.row.row}, Место №{self.place}, {self.row.hall.name}"


class Ticket(models.Model):
    """ticket of place"""
    taken = models.BooleanField(default=False)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.place} - {self.session}"

    class Meta:
        unique_together = ('place', 'session')


class CinemaImages(models.Model):
    name = models.CharField(max_length=50)
    cinema = models.ForeignKey(Cinema, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=f'cinema/{cinema.name}')

    def __str__(self):
        return self.name


class SocialLinks(models.Model):
    name = models.CharField(max_length=50)
    link = models.URLField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=f'social_images/{city.name}', null=True, blank=True)

    def __str__(self):
        return self.name


class TitleQuestion(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Answer(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()
    tq = models.ForeignKey(TitleQuestion, on_delete=models.CASCADE)

    def __str__(self):
        return self.question

order/models.py
from django.db import models

import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw

from user.models import AdvUser

# Create your models here.


class Order(models.Model):
    # phone = models.CharField(max_length=11)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True)
    qr_code = models.ImageField(upload_to='qr_codes/%Y/%M/%M', blank=True)
    url = models.CharField(max_length=200, blank=True, default=f'http://127.0.0.1:8000/')
    user = models.ForeignKey(AdvUser, on_delete=models.CASCADE, null=True, blank=True)
    discount = models.IntegerField(default=0)
    price = models.IntegerField(default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_row_set(self):
        return {ticket.place.row.row for ticket in self.ticket_set.all()}

    def get_total_cost(self):
        return sum(ticket.session.price for ticket in self.ticket_set.all())

    def save(self, *args, **kwargs):
        self.url = f'http://127.0.0.1:8000/orenburg/payment/done/{self.id}'
        qrcode_img = qrcode.make(self.url)
        canvas = Image.new('RGB', (400, 400), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname = f'qr_code-{self.id}.png'
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        self.qr_code.save(fname, File(buffer), save=False)
        canvas.close()
        super().save(*args, **kwargs)


# class OrderItem(models.Model):
#     order = models.ForeignKey(Order, on_delete=models.CASCADE)
#     ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return f'{self.id}'

user/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, edit
from django.contrib.auth import authenticate, login, views

from .models import AdvUser
from order.models import Order
from movie.models import Ticket
from order.forms import CustomUserCreationForm, OrderCreateForm
from movie.session import SessionTickets
from django.core.cache import cache
from django.conf import settings

import redis

from .forms import LoginForm, AdvUserUpdateForm, RegisterForm
from order.forms import PhoneForm


r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=1)


class CheckEmail(View):
	def post(self, request):
		email = request.POST.get('email', '')
		password = request.POST.get('password', '')
		form = PhoneForm(request.POST)
		# if form.is_valid():
		try: 
			AdvUser.objects.get(email=email)
			l = LoginForm(data={'username': email, 'password': password})
			if l.is_valid():
				user = authenticate(email=email, password=password)
				login(request, user)
				return redirect('account')
			request.session['error_password'] = l.errors
			request.session['error_all'] = l.non_field_errors()
			return redirect('check_email')		


		except AdvUser.DoesNotExist: 
			print('asss')
			reg = RegisterForm(data={'username': email, 'password1': password, 'password2': password})
			if reg.is_valid():
				AdvUser.objects.create_user(email=email, password=password)
				user = authenticate(email=email, password=password)
				login(request, user)
				return redirect('account')
			request.session['error_password'] = reg.errors
			request.session['error_all'] = reg.non_field_errors()
			return redirect('check_email')	

		# print(request.POST)

		# form = PhoneForm(data=request.POST)
		# if form.is_valid():
		# 	email = request.POST.get('email', '')
		# 	password = request.POST.get('password', '')
		# 	user = authenticate(email=email, password=password)
		# 	if user:
		# 		login_form = LoginForm(request.POST)
		# 		if login_form.is_valid():
		# 			login(request, user)
		# 			return redirect('account')
		# 		else:
		# 			request.session['error_password'] = form.errors
		# 			return redirect('order_create', slug=r.get('const_city').decode())
		# 	else: 
		# 		register_form = RegisterForm(data={'username': email,
		# 										   'password1': password,
		# 										   'password2': password})
		# 		if register_form.is_valid():
		# 			AdvUser.objects.create_user(email=email, password=password)
		# 			user = authenticate(email=email, password=password)
		# 			login(request, user)
		# 			return redirect('account')
		# 		else:
		# 			request.session['error_password'] = form.errors
		# 			return redirect('order_create', slug=r.get('const_city').decode())
		# request.session['error_password'] = form.errors
		# return redirect('order_create', slug=r.get('const_city').decode())


	def get(self, request):
		form = PhoneForm()
		errors2 = request.session.get('error_password', '')
		if request.session.get('error_password', ''):
			del request.session['error_password']

		errors3 = request.session.get('error_all', '')
		if request.session.get('error_all', ''):
			del request.session['error_all']

		return render(request, 'user/check_email.html', {'form': form,
														 'errors2': errors2,
                                                      	 'errors3': errors3})


class Account(View):
	def get(self, request):
		return render(request, 'user/account.html')


class CheckPhone(View):
	def post(self, request):
		email = request.POST.get('email', '')
		password = request.POST.get('password', '')
		form = PhoneForm(request.POST)
		# if form.is_valid():
		try: 
			AdvUser.objects.get(email=email)
			l = LoginForm(data={'username': email, 'password': password})
			if l.is_valid():
				user = authenticate(email=email, password=password)
				login(request, user)
				return redirect('use_bonuses')
			request.session['error_password'] = l.errors
			request.session['error_all'] = l.non_field_errors()
			return redirect('order_create', slug=r.get('const_city').decode())		


		except AdvUser.DoesNotExist: 
			print('asss')
			reg = RegisterForm(data={'username': email, 'password1': password, 'password2': password})
			if reg.is_valid():
				AdvUser.objects.create_user(email=email, password=password)
				user = authenticate(email=email, password=password)
				login(request, user)
				return redirect('use_bonuses')
			request.session['error_password'] = reg.errors
			request.session['error_all'] = reg.non_field_errors()
			return redirect('order_create', slug=r.get('const_city').decode())	
	
		# request.session['error_password'] = form.errors
		# return redirect('order_create', slug=r.get('const_city').decode())		

class CreateUserOrderView(View):

	def get(self, request):
		user = request.user
		bonuses = user.bonuses

		print('---------->', user)

		tickets = SessionTickets(request)
		total_price = tickets.total_price()
		one_price = tickets.one_price()

		return render(request, 'user/use_bonuses.html', {'bonuses': bonuses,
														 'total_price': total_price,
														 'one_price': one_price,
														 'ticket_count': tickets.len()})

	def post(self, request):
		bonus = request.POST.get('bonus', '')
		# request.session['bonus'] = bonus
		# return redirect('process', slug=slug)
		print(type(bonus), bonus)
		slug = r.get('const_city').decode()
		tickets = SessionTickets(request)
		user = request.user 
		if bonus:
			if user.bonuses >= tickets.total_price():
				# и вычитать бонусы только после оплаты
				bonuses = tickets.total_price()
				price = 0
			elif user.bonuses < tickets.total_price():
				price = tickets.total_price() - user.bonuses
				bonuses = user.bonuses

			order = Order.objects.create(email=user.email, user=user, price=price, discount=bonuses)
			for item in tickets.get():
				ticket = Ticket.objects.get(id=item)
				ticket.order = order
				ticket.save()
			tickets.clear()
			request.session['order_id'] = order.id
			return redirect('process', slug=slug)
		else:
			price = tickets.total_price()
			# потом переделать чтобы бонусы добавлялись только после оплаты
			order = Order.objects.create(email=user.email, user=user, price=price)
			for item in tickets.get():
				ticket = Ticket.objects.get(id=item)
				ticket.order = order
				ticket.save()
			tickets.clear()
			request.session['order_id'] = order.id
			return redirect('process', slug=slug)
			

    # def post(self, request, slug):
    #     tickets = SessionTickets(request)
    #     form = OrderCreateForm(request.POST)
    #     if form.is_valid():
    #         order = form.save()
    #         for item in tickets.get():
    #             ticket = Ticket.objects.get(id=item)
    #             ticket.order = order
    #             ticket.save()
    #         tickets.clear()
    #         request.session['order_id'] = order.id
    #         return redirect('process', slug=slug)
    #     messages.add_message(request, messages.ERROR, "Форма не валидный")
    #     return redirect('order_create', slug=slug)


def lol(request, slug):
	print(request.user)
	return render(request, '1.html')


class UpdateAccountView(edit.UpdateView):
	model = AdvUser
	form_class = AdvUserUpdateForm
	success_url = '/account/acoount/'
	template_name = 'user/update_account.html'

movie/templates/user/account.html
{% extends 'base.html' %}

{% block content %}
<div class="container-my">
	<div class="row">
		<div class="col-lg-3 col-sm-12">
			<h2>Личный кабинет</h2>
			<p>{{ user }}</p>
			<p>{{ user.bonuses }}</p>
			<a class="btn btn-place-usual mt-1" href="{% url 'update_user' pk=user.id %}">Edit account</a>
			<a class="btn btn-place-danger mt-1" href="{% url 'logout' %}">Log Out</a>
		</div>
		<div class="col-lg-9 col-sm-12">
			<h1>Заказы</h1>
			<div class="row">
			{% for order in user.order_set.all %}
				<div class="col-lg-4 col-sm-12">
					<div class="order text-white">
			            <p>{{ order.ticket_set.first.session.movie.age_limit }}</p>
			            <p><strong>{{ order.ticket_set.first.session.movie }}</strong></p>
			            <p>{{ order.ticket_set.first.session.format }}, {{ order.ticket_set.first.place.row.hall.name }}</p>
			            <p>{{ order.ticket_set.first.session.cinema }}</p>
			            
			            <table>
			                <thead>
			                    <tr>
			                        <th>Дата/Время</th>
			                    </tr>
			                </thead>
			                <tbody>
			                    <tr>
			                        <th>
			                            {{ order.ticket_set.first.session.date }}
			                            {{ order.ticket_set.first.session.time }}
			                        </th>
			                    </tr>
			                </tbody>
			            </table>
			            <table>
			                <thead>
			                    <tr>
			                        <th colspan="2">Ряд</th>
			                        <th></th>
			                        <th></th>
			                        <th>Место</th>
			                    </tr>
			                </thead>
			                <tbody>
			                    {% for row in order.get_row_set %}
			                   <tr>
			                       <th colspan="2">
			                           {{ row }}
			                       </th>
			                       <th></th>
			                       <th></th>
			                       <th>
			                       {% for ticket in order.ticket_set.all %}
			                           {% if ticket.place.row.row == row %}
			                              {{ ticket.place.place }},
			                           {% endif %}
			                       {% endfor %}
			                       </th>
			                   </tr>
			                    {% endfor %}
			                </tbody>
			            </table>
			            
			            <p>№{{ order.id }}</p>
			            <p>Общая стоимость {{ order.price }}</p>
			            <img width="280" src="{{ order.qr_code.url }}">
			        </div>
				</div>
				
			{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

movie/templates/user/check_email.html
{% extends 'base.html' %}

{% block content %}

<div class="container-my">
	<div class="row m-5">
		<div class="col-lg-4"></div>
		<div class="col-lg-4">
			<h1>Зайти/Зарегистрироваться</h1>
			<form action="" method="post">
				{% csrf_token %}
				<p>{{ form.email }}</p>
                {% for error in errors2.email %}
                <p class="text-danger">{{ error }}</p>
                {% endfor %}
                <br>
                <p>{{ form.password }}</p>
                {% for error in errors2.password2 %}
                <p class="text-danger">{{ error }}</p>
                {% endfor %}
                {% for error in errors2.password %}
                <p class="text-danger">{{ error }}</p>
                {% endfor %}
                {% for error in errors3 %}
                <p class="text-danger">{{ error }}</p>
                {% endfor %}
				<button type="submit" class="btn btn-place">logIn/SignIn</button>
			</form>
			<a href="{% url 'password_reset' %}" class="text-danger">Забыли пароль?</a>
		</div>
	</div>
</div>

{% endblock %}

movie/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container-my">
	<div class="row">
		<div class="col">
			{{ email }}
			<form action="">
				{% csrf_token %}
				<!-- <input type="email" name="email" value="{{ email }}" hidden>
				<input type="password" name="password"> -->
				{{ form.as_p }}
				<button class="btn btn-success" type="submit">login</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

movie/templates/user/password_reset.html
{% extends 'base.html' %}

{% block content %}
<div class="container-my">
	<div class="row m-5">

		<div class="col-lg-4 col-sm-0"></div>
		<div class="col-lg-4 col-sm-12">
			<h1>Востановить пароль</h1>
			<form method="POST">
				{% csrf_token %}
				{{ form.email }}
				<button class="btn btn-place-usual mt-2" type="sumbit">Reset</button>
			</form>
			<a class="btn btn-place-danger mt-2" href="{% url 'account' %}">back</a>
		</div>
	</div>
</div>
{% endblock %}

movie/templates/user/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<div class="container-my">
	<div class="row">
		<div class="col">
			<p>Your password has been set. You may go ahead and log in now.</p>
			<a class="btn btn-place-usual" href="{% url 'check_email' %}">Log In</a>
		</div>
	</div>
</div>
{% endblock %}

movie/templates/user/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="container-my">
	<div class="row">
		<div class="col-lg-4 col-sm-0"></div>
		<div class="col-lg-4 col-sm-12">
			<h1>Назначить новый пароль</h1>
			<form method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="btn btn-place-usual">Reset</button>
			</form>
			<a class="btn btn-place-danger mt-2" href="{% url 'check_email' %}">back</a>
		</div>
	</div>
</div>
{% endblock %}

movie/templates/user/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<div class="container-my">
	<div class="row">
		<div class="col">
			<p>На ваш email было выслано письмо с говном</p>
		</div>
	</div>
</div>
{% endblock %}

movie/templates/user/password_reset_email.html
{% autoescape off %}
Уважаеммый {{ user.username }}!
Вы отправили запрос на сброс пароля. Чтобы выполнить сброс, пройдите по
этому интернет-адресу:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
До свидания!
С уважением, администрация сайта "Cinema 5"
{% endautoescape %}

movie/templates/user/update_account.html
{% extends 'base.html' %}

{% block content %}
<div class="container-my">
	<div class="row">
		<div class="col-4"></div>
		<div class="co-8l">
			<h1>Личный кабинет</h1>
			<form method="POST">
				{% csrf_token %}
				<p>{{ form.first_name }}</p>
				<p>{{ form.last_name }}</p>
				<p>{{ form.email }}</p>
				<button class="btn btn-place-usual" type="submit">Update</button>
			</form>
			<a class="btn btn-place-danger mt-2" href="{% url 'account' %}">back</a>
		</div>
	</div>
</div>
{% endblock %}

movie/templates/user/use_bonuses.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}

<div class="container-my">
<!-- <div class="row form-element"> -->
    <!-- <div class="col-4 near-buttons"></div> -->
    
    	<!-- <div id="first-button" class="col-4 text-center one-active">
        	
        	<p >Быстрая оплата</p>
        	
    	</div>
        
    	<div id="second-button" class="col-4 text-center form-element two">
    		
        	<p >Вход или регистрация</p>    
    		
    	</div> -->
    
<!-- </div> -->
<div class="row">
    <div class="col-4 near-buttons">
    	<div class="m-5">
	        <h4>Ваша заказ</h4>
	        <p>Билет {{ tickets_count }} шт. {{ total_price }} р.</p>
	        <hr>
        	<p>Всего: {{ total_price }} р.</p>
    	</div>
    </div>
    <div class="col-8">
        <div id="first">
            <div class="row">
                <div class="col-6">
                    <h3 class="mt-5 ml-5">Как работает бонусная система?</h3>
                    <p class="ml-5">С каждой покупкой начисляются бонусы - 5% от суммы билетов. Бонусы не сгорают.</p>
                    <p class="ml-5">Бонусными баллами можно оплачивать только стоимость билетов - частично или полностью. 1 бонус = 1 рубль.</p>
                    <p class="ml-5">На 3D-очки и товары скидки не распространяются.</p>
                </div>
                <div class="col-6">
                    <h3 class="mt-5 mx-5">Способ оплаты</h3>
                    <div class="custom-control custom-radio custom-control-inline  mx-5">
                      <input type="radio" id="customRadioInline1" name="customRadioInline1" class="custom-control-input" checked>
                      <label class="custom-control-label" for="customRadioInline1">Банковская карта</label>
                    </div>
                    <p class="mt-5 mx-5">Ваш счет {{ bonuses }} бонусов.</p>
                    <form name="bonuses" method="post" class="mx-5">
                        {% csrf_token %}
                        {% if bonuses %}
                        <div class="custom-control custom-switch">
                          <input name="bonus" type="checkbox" class="custom-control-input" id="customSwitch1">
                          <label class="custom-control-label" for="customSwitch1">Использовать {{ bonuses }} бонусов</label>
                        </div>
                        {% else %}
                        <div class="custom-control custom-switch">
                          <input name="bonusss" type="checkbox" class="custom-control-input" disabled id="customSwitch2">
                          <label class="custom-control-label" for="customSwitch2">Использовать {{ bonuses }} бонусов</label>
                        </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-4 near-buttons"></div>
	<div class="col-8">
		<p class="ml-5 mt-5">Продолжая, я принимаю политику конфиденцальности и пользовательское соглашение.</p>
        <div>  
		  <a class="ml-5 " href="{% url 'cancel_tickets' city_slug %}">Отмена</a><button id="btn-right" class="btn-place btn">Далее</button>
        </div>
	</div>
</div>
</div>
<script>
let btn_right = document.getElementById('btn-right') 
let form = document.querySelector('form[name=bonuses]')
btn_right.addEventListener('click', e => {
    console.log('sdfsdf')
    form.submit()
})
</script>
{% endblock %}