cinema5/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('auth/', include('allauth.urls')),
    # path('auth/', include('django.auth.contrib')),
    path('', include('movie.urls')),
    path('<slug:slug>/order/', include('order.urls')),
    path('<slug:slug>/payment/', include('payment.urls')),
    path('account/', include('user.urls')),
    path('<slug:city_slug>/promotion/', include('shares.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movie/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.CitiesView.as_view(), name='cities'),
    path('<slug:slug>/today', views.MovieTodayView.as_view(), name='today'),
    path('<slug:slug>/children', views.MovieChildrenTodayView.as_view(), name='children'),
    path('<slug:slug>/date', views.MovieDateView.as_view(), name='filter'),
    path('<slug:slug>/tomorrow', views.MovieTomorrowView.as_view(), name='tomorrow'),
    path('<slug:slug>/soon', views.MovieSoonView.as_view(), name='soon'),
    path('<slug:slug>/today/<int:pk>', views.MovieDetailToday.as_view(), name='movie_detail_today'),
    path('<slug:slug>/tomorrow/<int:pk>', views.MovieDetailTomorrow.as_view(), name='movie_detail_tomorrow'),
    path('<slug:slug>/soon/<int:pk>', views.MovieDetailSoon.as_view(), name='movie_detail_soon'),
    path('<slug:slug>/date/<str:date>/<int:pk>', views.MovieDetailDate.as_view(), name='movie_detail_date'),
    path('<slug:slug>/shows/<int:pk>', views.SessionDetail.as_view(), name='session_detail'),
    path('<slug:slug>/shows/<int:pk>/create/ticket', views.CreateTicket.as_view(), name='create_ticket'),
    path('<slug:slug>/support/', views.SupportView.as_view(), name='support'),
    path('<slug:slug>/about/<int:pk>', views.AboutView.as_view(), name='about'),
    path('<slug:slug>/questions', views.TitleQuestionView.as_view(), name='questions'),
    path('<slug:slug>/questions/<int:pk>', views.AnswerDetailView.as_view(), name='answer'),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import (LogoutView, 
	PasswordResetView, PasswordResetConfirmView,
	PasswordResetDoneView, PasswordResetCompleteView)

from . import views
from .forms import AdvPasswordResetForm, AdvPasswordChangeForm

urlpatterns = [
	path('check', views.CheckPhone.as_view(), name='check_phone'),
	path('use_bonuses/', views.CreateUserOrderView.as_view(), name='use_bonuses'),
	path('check_email/', views.CheckEmail.as_view(), name='check_email'),
	path('acoount/', views.Account.as_view(), name='account'),
	path('account/logout', LogoutView.as_view(), name='logout'),
	path('account/password_reset', PasswordResetView.as_view(
		template_name='user/password_reset.html',
		email_template_name='user/password_reset_email.html',
		form_class=AdvPasswordResetForm
		), name='password_reset'),
	path('account/password_reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
		template_name='user/password_reset_confirm.html',
		form_class=AdvPasswordChangeForm), name='password_reset_confirm'),
	path('account/password_reset/done', PasswordResetDoneView.as_view(
		template_name='user/password_reset_done.html'), name='password_reset_done'),
	path('account/password_reset/complete', PasswordResetCompleteView.as_view(
		template_name='user/password_reset_complete.html'
		), name='password_reset_complete'),
	path('account/update_user/<int:pk>/', views.UpdateAccountView.as_view(), name='update_user'),
]

movie/models.py
from django.db import models
from django.utils import timezone

from order.models import Order
# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name


class Movie(models.Model):
    """Movie model"""
    title = models.CharField(max_length=100)
    city = models.ManyToManyField(City)
    age_limit = models.ForeignKey('AgeLimit', on_delete=models.CASCADE)
    country = models.CharField(max_length=200)
    genres = models.CharField(max_length=200, blank=True)
    director = models.CharField(max_length=100, blank=True, null=True)
    actors = models.CharField(max_length=200, blank=True)
    duration = models.TimeField(blank=True, null=True)
    poster = models.ImageField(upload_to='images/movies/%Y/%M/%D', blank=True)
    memorandum = models.DateField(auto_now_add=True, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField(auto_now=True)
    premier = models.BooleanField(default=False)
    carousel = models.ImageField(upload_to='images/movies/carusel/%Y/%M/%D', blank=True)
    is_carousel = models.BooleanField(default=False)
    trailer = models.URLField(blank=True, null=True)
    # cinemas = models.ManyToManyField('Cinema')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)


class AgeLimit(models.Model):
    """Age Limit model"""
    name = models.CharField(max_length=3)
    for_adults = models.BooleanField(default=True if name=='18+' else False)

    def __str__(self):
        return self.name


class Cinema(models.Model):
    """Cinema model"""
    name = models.CharField(max_length=100)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    phone = models.CharField(max_length=11, default='')
    information = models.TextField(default='')
    halls = models.IntegerField(default=0)
    places = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name} - {self.city}"


class Session(models.Model):
    """Session model"""
    date = models.DateField()
    time = models.TimeField()
    format = models.CharField(max_length=10)
    hall = models.ForeignKey('Hall', on_delete=models.CASCADE)
    cinema = models.ForeignKey(Cinema, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    # city = models.ForeignKey(City, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    price = models.IntegerField(default=228)

    def __str__(self):
        return f"{self.movie.title} - {self.date} - {self.time} - {self.cinema}"


class Hall(models.Model):
    """cinema hall"""
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Row(models.Model):
    row = models.IntegerField()
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

    def __str__(self):
        return f"ряд {self.row} - {self.hall.name}"


class Place(models.Model):
    """place in the cinema hall"""
    row = models.ForeignKey(Row, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    empty = models.BooleanField(default=False)
    place = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"Ряд №{self.row.row}, Место №{self.place}, {self.row.hall.name}"


class Ticket(models.Model):
    """ticket of place"""
    taken = models.BooleanField(default=False)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.place} - {self.session}"

    class Meta:
        unique_together = ('place', 'session')


class CinemaImages(models.Model):
    name = models.CharField(max_length=50)
    cinema = models.ForeignKey(Cinema, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=f'cinema/{cinema.name}')

    def __str__(self):
        return self.name


class SocialLinks(models.Model):
    name = models.CharField(max_length=50)
    link = models.URLField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=f'social_images/{city.name}', null=True, blank=True)

    def __str__(self):
        return self.name


class TitleQuestion(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Answer(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()
    tq = models.ForeignKey(TitleQuestion, on_delete=models.CASCADE)

    def __str__(self):
        return self.question

movie/forms.py
from django import forms
from django.db.utils import IntegrityError

from .models import Ticket, Place


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('place', 'session')

    def __init__(self, *args, **kwargs):
        self.places = args[0].getlist('place')
        super().__init__(*args, **kwargs)

    def save(self):
        tickets = []
        for place in self.places:
            tickets.append(Ticket.objects.create(place=Place.objects.get(id=place),
                                                 session=self.cleaned_data['session']))
        return [ticket.id for ticket in tickets]

movie/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from datetime import date, timedelta, datetime
from django.utils import timezone
from django.views.generic import View, ListView, DetailView, CreateView
from django.http import JsonResponse
from django.db import IntegrityError
from django.contrib import messages
from django.core.cache import cache
from django.conf import settings
from django.db.models import Q

import re
import redis

from .session import SessionTickets
from .models import *
from .utils import *
from .forms import TicketForm
from .tasks import delete_tickets_if_invalid


r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=1)


class CityMixin(DetailView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['city'] = City.objects.get(slug=str(self.request.path.split('/')[1]))
        d = self.request.GET.get('date', None)
        context['city_slug'] = str(self.request.path.split('/')[1])
        if d:
            context['date_form'] = d
            c = context['city_slug']
            m = kwargs['object']
            d = date(*[int(i) for i in d.split('-')])
            sessions = SessionFilterDate().get_sessions(d, c)
            sessions = sessions.filter(movie=m)
            sessions = [sessions.filter(cinema=cinema) for cinema in context['city'].cinema_set.all()]
            context['sessions2'] = sessions
            context['sessions_flag'] = True
            # print([i for i in context['sessions']])
        # print([cinema for cinema in context['city'].cinema_set.all()])
        # print(context)
        return context


class CitiesView(View):
    queryset = City.objects.all()
    template_name = 'movie/city_list.html'

    def get(self, request):
        if r.get('temp_city'):
            return redirect('today', slug=r.get('temp_city').decode())
        if r.get('const_city'):
            r.delete('const_city')
        # if cache.has_key('city'):
        #     city = cache.get('city')
        #     return redirect('today', slug=city)
        return render(request, self.template_name, {'object_list': self.queryset})


class MovieTodayView(SessionFilterToday, ListView):

    def get_queryset(self):
        city_slug = self.request.path.split('/')[1]
        
        if not r.get('temp_city'):
            r.setex('temp_city', timedelta(minutes=60), city_slug)
        r.set('const_city', city_slug)
        # self.request.session['city'] = city_slug
        # if not cache.has_key('city'):
        #     cache.set('city', city_slug, 60 * 15)
        queryset = Movie.objects.filter(session__in=self.get_sessions(city_slug))
        return queryset.distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['today'] = True
        return context


class MovieChildrenTodayView(SessionFilterToday, ListView):
    # template_name = 'movie/children_list.html'

    def get_queryset(self):
        city_slug = self.request.path.split('/')[1]
        queryset = Movie.objects.filter(session__in=self.get_sessions(city_slug))
        return queryset.filter(Q(age_limit__name='0+') | Q(age_limit__name='6+')).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['children'] = True
        return context


class MovieTomorrowView(SessionFilterTomorrow, ListView):
    def get_queryset(self):
        city_slug = self.request.path.split('/')[1]
        return Movie.objects.filter(session__in=self.get_sessions(city_slug)).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['tomorrow'] = True
        return context


class MovieSoonView(SessionFilterSoon, ListView):
    def get_queryset(self):
        city_slug = self.request.path.split('/')[1]
        return Movie.objects.filter(session__in=self.get_sessions(city_slug)).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['soon'] = True
        return context


class MovieDateView(SessionFilterDate, ListView):
    def get_queryset(self):
        city_slug = self.request.path.split('/')[1]
        d = date(*[int(i) for i in self.request.GET.get('date').split('-')])
        sessions = self.get_sessions(d, city_slug)
        return Movie.objects.filter(session__in=sessions).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['city_slug'] = str(self.request.path.split('/')[1])
        context['date'] = (date(*[int(i) for i in self.request.GET.get('date').split('-')]), context['city_slug'])
        context['date0'] = context['date'][0]
        return context


class MovieDetailToday(CityMixin, SessionFilterToday):
    model = Movie

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['today'] = True
        sessions = self.get_sessions(city_slug=context['city_slug']).filter(movie=kwargs['object'])
        sessions = [sessions.filter(cinema=cinema) for cinema in context['city'].cinema_set.all()]
        context['sessions'] = sessions
        return context


class MovieDetailTomorrow(CityMixin, SessionFilterTomorrow):
    model = Movie

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['tomorrow'] = True
        sessions = self.get_sessions(city_slug=context['city_slug']).filter(movie=kwargs['object'])
        context['sessions'] = [sessions.filter(cinema=cinema) for cinema in context['city'].cinema_set.all()]
        return context


class MovieDetailSoon(CityMixin, SessionFilterSoon):
    model = Movie

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['soon'] = True
        sessions = self.get_sessions(city_slug=context['city_slug']).filter(movie=kwargs['object'])
        context['sessions'] = [sessions.filter(cinema=cinema) for cinema in context['city'].cinema_set.all()]
        return context


class MovieDetailDate(CityMixin, SessionFilterDate):
    model = Movie

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['city_slug'] = str(self.request.path.split('/')[1])
        context['date'] = (date(*[int(i) for i in self.request.path.split('/')[3].split('-')]), context['city_slug'])
        sessions = self.get_sessions(city_slug=context['city_slug'], date=context['date'][0]).filter(movie=kwargs['object'])
        context['sessions'] = [sessions.filter(cinema=cinema) for cinema in context['city'].cinema_set.all()]
        return context


class SessionDetail(DetailView):
    model = Session

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['errors'] = messages.get_messages(self.request)
        return context


class CreateTicket(View):
    def post(self, request, slug, pk):
        session = SessionTickets(request)
        form = TicketForm(request.POST)
        if form.is_valid():
            try:
                tickets = form.save()
                now = timezone.now()
                delete_tickets_if_invalid.apply_async([tickets], eta=now + timedelta(minutes=1))
            except IntegrityError:
                messages.add_message(request, messages.ERROR, "Билет(ы) уже куплены")
                return redirect('session_detail', slug=slug, pk=pk)
            session.add(tickets)
            return redirect('order_create', slug=slug)
        else:
            messages.add_message(request, messages.ERROR, "Билет(ы) уже куплены")
            return redirect('session_detail', slug=slug, pk=pk)


class SupportView(View):
    def get(self, request, slug):
        return render(request, 'about/support.html')


class AboutView(CityMixin):
    model = Cinema

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cinemas'] = Cinema.objects.filter(city__slug=context['city_slug'])
        context['first'] = kwargs['object'].cinemaimages_set.first()
        context['rest'] = kwargs['object'].cinemaimages_set.all()[1:]
        return context


class TitleQuestionView(ListView):
    model = TitleQuestion


class AnswerDetailView(DetailView):
    model = Answer

    def get(self, request, *args, **kwargs):
        detail = self.get_object()
        return JsonResponse({'answer': detail.answer}, safe=False)

movie/templates/movie/cinema_detail.html
{% extends "base.html" %}

{% block title %}{{ cinema.name }}{% endblock %}
{% block content %}
<div class="container-my">
    <div>
        {% for cinema in cinemas %}
        <a href="{% url 'about' city_slug cinema.pk %}">{{ cinema.name }}</a>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-6">
            <h2>О кинотеатре</h2>
            <p>{{ cinema.information }}</p>
            <p>{{ cinema.halls }} кинозалов {{ cinema.places }} место</p>
        </div>
         <div class="col-6">
            <h2>Группы в социальных сетях</h2>
            <p>Рассказываем об интересных премьерах, проводим акции, отвечаем на вопросы
                {% for link in cinema.city.sociallinks_set.all %}<a href="{{ link.link }}">{{ link.name }}</a>, {% endfor %}</p>

        </div>
         <div class="col-6">
            <h2>Дирекция кинотеатра</h2>
            <p>Телефон: {{ cinema.phone }}</p>
        </div>
    </div>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ first.image.url }}" class="d-block w-100" alt="...">
    </div>
      {% for image in rest %}
    <div class="carousel-item">
      <img src="{{ image.image.url }}" class="d-block w-100" alt="...">
    </div>
      {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
{% endblock %}

movie/templates/movie/city_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <title>Cinema 5 - {% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <h2 class="mt-3 ml-5">Выберите город</h2>
                <table class="table mt-4">
                    
                      <tbody>
                         {% for city in  object_list %}
                        <tr>
                          <td><a class="text-dark" href="{% url 'today' city.slug %}">{{ city.name }}</a></td>
                        </tr>
                          {% endfor %}
                        
                      </tbody>
                </table>    
            </div>
        </div>
    </div>
</body>

movie/templates/movie/movie_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container-my">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-3">        
            <div class="image-detail">
                <img   src="{{ movie.poster.url }}">
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-9">
            <h5 class="md-color">{{ movie.age_limit }}</h5>
            <h3><strong>{{ movie.title }}</strong></h3>
            <table class="mb-2">
                <tr {% if movie.country %}>
                    <td class="md-color">Производство</td>
                    <td class="pl-4">{{ movie.country }}</td>
                </tr {% endif %}>
                <tr {% if movie.genres %}>
                    <td class="md-color">Жанры</td>
                    <td class="pl-4">{{ movie.genres }}</td>
                </tr {% endif %}>
                <tr {% if movie.director %}>
                    <td class="md-color">Режиссёр</td>
                    <td class="pl-4">{{ movie.director }}</td>
                </tr {% endif %}>        
                <tr {% if movie.actors %}>
                    <td class="md-color">В главных ролях</td>
                    <td class="pl-4">{{ movie.actors }}</td>
                </tr {% endif %}>
                <tr {% if movie.duration %}>
                    <td class="md-color">Длительность</td>
                    <td class="pl-4">{{ movie.duration }}</td>
                </tr {% endif %}>
                <tr {% if movie.memorandum %}>
                    <td class="md-color">Меморандум</td>
                    <td class="pl-4">{{ movie.memorandum }}</td>
                </tr {% endif %}>
            </table>
            <p>{{ movie.description }}</p>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col">
            {% if soon %}
            {% else %}
            <form method="get">
                <input type="date" name="date">
                <input type="submit">
            </form>
            {% endif %}
            {% if sessions2 %}
            {% for cinema in sessions2 %}
                <div class="col-12">
                    <div {% if cinema.first %} class="session-detail-back">
                        <div class="row">
                            <div class="col-2">
                                <strong>{{ cinema.first.cinema.name }}</strong>
                                <p>{{ cinema.first.cinema.information }}</p>
                            </div>
                            <div class="col-10">
                                {% for session in cinema  %}
                                <a href="{% url 'session_detail' city_slug session.id %}">
                                    <div class="session">
                                        <h4>{{ session.time|time:'H:i' }}</h4>
                                        <p>от {{ session.price }} Р</p>
                                        <p>{{ session.hall }}</p>
                                    </div>
                                </a>
                                {% endfor %}
                            </div>
                        </div>    
                    </div {% endif %}>

                </div>
            {% endfor %} 
            {% else %}
            <div class="row">
            {% for cinema in sessions %}
                <div class="col-12">
                    <div {% if cinema.first %} class="session-detail-back">
                        <div class="row">
                            <div class="col-2">
                                <strong>{{ cinema.first.cinema.name }}</strong>
                                <p>{{ cinema.first.cinema.information }}</p>
                            </div>
                            <div class="col-10">
                                {% for session in cinema  %}
                                <a href="{% url 'session_detail' city_slug session.id %}">
                                    <div class="session">
                                        <h4>{{ session.time|time:'H:i' }}</h4>
                                        <p>от {{ session.price }} Р</p>
                                        <p>{{ session.hall }}</p>
                                    </div>
                                </a>
                                {% endfor %}
                            </div>
                        </div>    
                    </div {% endif %}>

                </div>
            {% endfor %}    
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

movie/templates/movie/session_detail.html
{% extends "base.html" %}
{% load movie_extras %}

{% block content %}


<div class="container-my">

<form name="ticket" action="{% url 'create_ticket' city_slug session.id  %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="session" value="{{ session.id }}">
<div class="row m-5">
    <div class="col-9">
        <div class="row mr-5">
        {% for row in session.hall.row_set.all %}
            <div class="col-12">
                <div class="row">
                    <div class="col-1">
                        <div class="row-text">{{ row.row }}</div>
                    </div>
                    <div class="col-10 text-center">
                        {% for place in row.place_set.all %}
                        <div class="seat">
                        {% if place.place %}
                        <div class="{% if place.id|is_ticket:session.id %}place-bought{% else %}place{% endif %}" onclick="create_ticket({{ place.id }})">
                        <span id="{{ place.id }}">
                            <input type="checkbox" name="place" value="{{ place.id }}" hidden>
                            <label data-title="{{place.row.row}} ряд, {{ place.place }} место {{ session.price }} р.">{{ place.place }}</label>
                        </span>
                        </div>
                        {% else %}
                        <div class="place-empty">
                        
                        </div>
                        {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    <div class="col-1">
                        <div class="row-text">{{ row.row }}</div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="col-12 text-center">
            <div class="seat">
            <div class="place-bought">
                <label></label>
            </div> 
            </div><div class="place-text"> - занято</div>
            <div class="seat">
            <div class="place-2">
                <label></label>
            </div> 
            </div><div class="place-text"> - свободно</div>
            <div class="seat">
            <div class="place-your">
                <label></label>
            </div> 
            </div><div class="place-text">- ваше место</div>
        </div>
        </div>
    </div>
    <div class="col-3">
        <h5><strong>{{ session.movie }} {{ session.movie.age_limit }}</strong></h5>
        <p>{{ session.date }} {{ session.time }}</p>
        <p>{{ session.format }} {{ session.hall }}</p>
        <p><nobr id=price>0</nobr> рублей</p>
        <button class="btn btn-place" type="submit">Далее</button>
    </div>
</div>
</form>
</div>
<script>
function create_ticket(id) {
	let span = document.getElementById(`${id}`)
	let input = span.firstElementChild
	let label = span.lastElementChild

    let cost = {{ session.price }}
    let price = document.getElementById('price')

    // console.log(price.innerHTML, typeof +price.innerHTML, cost, typeof cost) 
	input.checked = !input.checked
    // console.log(input.checked)
    if (input.checked) {
        price.innerHTML = +price.innerHTML + cost
    }  else {
        // console.log(price.innerHTML)
        price.innerHTML = +price.innerHTML - cost
    }
	// if (input.checked) {
	// 	label.style.background = 'blue'
	// } else {
	// 	label.style.background = ''
	// }
	// console.log(id)
	// console.log(input.focus)
	// console.log(input.checked)
}
</script>
{% endblock %}

movie/templates/movie/titlequestion_list.html
{% extends 'base.html' %}

{% block title%}Вопросы{% endblock %}

<style>
    a{
        cursor: pointer;
    }
</style>
{% block content %}
<div class="container-my">
    <div class="row">
        <div class="col point">
            {% for title_questions in object_list %}
            <p class="point" style="cursor:pointer" onclick="lol({{ title_questions.id }})">{{ title_questions }}</p>
            <ul class="questions-{{title_questions.id}}" hidden>
                {% for question in  title_questions.answer_set.all %}
                <li><a style="cursor: pointer;" onclick="detail('{% url 'answer' city_slug question.id %}')">{{ question.question }}</a></li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        <div id="div" class="col">
            {% block pre-content %}
            {% endblock %}
        </div>
    </div>
</div>
<script>
function lol (id) {
    document.querySelectorAll(`ul.questions-${id}`).forEach(q => q.hidden = !q.hidden )
}
let div = document.getElementById('div')
function detail(url) {
    fetch(`http://127.0.0.1:8000${url}`, {
        method: 'GET'}).then(response => response.json())
        .then(json => render(json))
        .catch(error => console.error(error))
}

function render(data) {
    div.innerHTML = data.answer
}

</script>
{% endblock %}